webtalk_init -webtalk_dir C:\\VivadoProjects\\ece544_proj3\\ece544_proj3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 1 08:11:30 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "hncmh68lbsriu38t8rg06i2c68" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_43" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1496276353560" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1496276353560"
webtalk_add_data -client sdk -key uid -value "1496276389087" -context "sdk\\\\bsp/1496276389087"
webtalk_add_data -client sdk -key hwid -value "1496276353560" -context "sdk\\\\bsp/1496276389087"
webtalk_add_data -client sdk -key os -value "xilkernel" -context "sdk\\\\bsp/1496276389087"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1496276389087"
webtalk_add_data -client sdk -key uid -value "1496277809966" -context "sdk\\\\bsp/1496277809966"
webtalk_add_data -client sdk -key hwid -value "1496276353560" -context "sdk\\\\bsp/1496277809966"
webtalk_add_data -client sdk -key os -value "xilkernel" -context "sdk\\\\bsp/1496277809966"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1496277809966"
webtalk_add_data -client sdk -key uid -value "1496277816074" -context "sdk\\\\application/1496277816074"
webtalk_add_data -client sdk -key hwid -value "1496276353560" -context "sdk\\\\application/1496277816074"
webtalk_add_data -client sdk -key bspid -value "1496277809966" -context "sdk\\\\application/1496277816074"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1496277816074"
webtalk_add_data -client sdk -key os -value "xilkernel" -context "sdk\\\\application/1496277816074"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1496277816074"
webtalk_transmit -clientid 1731002354 -regid "" -xml C:\\VivadoProjects\\ece544_proj3\\ece544_proj3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\VivadoProjects\\ece544_proj3\\ece544_proj3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\VivadoProjects\\ece544_proj3\\ece544_proj3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
