# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/n4DDRfpga.xdc

# Block Designs: bd/embsys/embsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys}]

# IP: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0}]

# IP: bd/embsys/ip/embsys_nexys4IO_0_0/embsys_nexys4IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_nexys4IO_0_0 || ORIG_REF_NAME==embsys_nexys4IO_0_0}]

# IP: bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodENC_0_0 || ORIG_REF_NAME==embsys_PmodENC_0_0}]

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodOLEDrgb_0_0 || ORIG_REF_NAME==embsys_PmodOLEDrgb_0_0}]

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}]

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}]

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0}]

# IP: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0}]

# IP: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0}]

# IP: bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_fit_timer_0_0 || ORIG_REF_NAME==embsys_fit_timer_0_0}]

# IP: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0}]

# IP: bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timebase_wdt_0_0 || ORIG_REF_NAME==embsys_axi_timebase_wdt_0_0}]

# IP: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0}]

# IP: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0}]

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_0}]

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_0}]

# IP: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_0 || ORIG_REF_NAME==embsys_lmb_bram_0}]

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_0/embsys_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_0}]

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0}]

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_0/embsys_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_0 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_0}]

# IP: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0}]

# IP: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0}]

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0}]

# IP: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_xbar_0 || ORIG_REF_NAME==embsys_xbar_0}]

# IP: bd/embsys/ip/embsys_PmodHB3_0_2/embsys_PmodHB3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodHB3_0_2 || ORIG_REF_NAME==embsys_PmodHB3_0_2}]

# XDC: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_0 || ORIG_REF_NAME==embsys_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc_debug.xdc

# XDC: bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_PmodOLEDrgb_0_0 || ORIG_REF_NAME==embsys_PmodOLEDrgb_0_0}] {/inst }]/inst ]]

# XDC: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_0 || ORIG_REF_NAME==embsys_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_0 || ORIG_REF_NAME==embsys_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_fit_timer_0_0/embsys_fit_timer_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_0 || ORIG_REF_NAME==embsys_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_axi_timebase_wdt_0_0 || ORIG_REF_NAME==embsys_axi_timebase_wdt_0_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_0 || ORIG_REF_NAME==embsys_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_0 || ORIG_REF_NAME==embsys_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_0 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_mdm_1_0 || ORIG_REF_NAME==embsys_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0_ooc_trace.xdc

# XDC: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_0 || ORIG_REF_NAME==embsys_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc

# XDC: bd/embsys/embsys_ooc.xdc
